name: twitcher
channels:
- birdhouse
- defaults
- conda-forge
dependencies:
- python=2.7
- curl
- pyopenssl
- cryptography
- mako
- pyyaml
- icu=56
# tests
- pytest
- flake8
- mock
- pbr
- webtest
# sphinx
- sphinx
# twitcher
- argcomplete
- lxml=3.7
- libxslt=1.1.29
- paste
- pastedeploy
- requests
- requests-file
- requests-oauthlib
- webob
# pywps
#- pywps=4.0.0
#- owslib (waiting 0.17.0 which implement wps with custom headers)
# nginx, supervisor
- nginx=1.10
- supervisor=3
- gunicorn=19.8.1
- gevent=1.2
# mongodb
- pymongo=3
- mongodb=3.4
- openssl
- lxml=3.7
- libxslt=1.1.29
- celery
- cornice
- colander
- pip:
  - -e git+https://github.com/geopython/pywps#egg=pywps
  - genshi==0.7
  - pyramid-rpc
  - pyramid-mako
  - pyramid-celery
  - sphinx-autoapi
  - -e git+https://github.com/huard/sphinx-autodoc-pywps.git#egg=sphinx_autodoc_pywps
  - ziggurat_foundations
  - bcrypt
  - https://github.com/geopython/OWSLib/archive/master.zip
  - cornice_swagger
  - flufl.enum
